<a href="https://colab.research.google.com/github/Samriddhi743/CP/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Creating NumPy Arrays using np.array();

In [1]:
import numpy as np

# Creating a NumPy array from a Python list
arr = np.array([1, 2, 3, 4, 5])
print("Array created using np.array():", arr)

Array created using np.array(): [1 2 3 4 5]


Creating arrays of zeros, ones, and random numbers:

In [2]:
# Creating an array of zeros
zeros_arr = np.zeros((3, 3))
print("Array of zeros:")
print(zeros_arr)

# Creating an array of ones
ones_arr = np.ones((2, 4))
print("Array of ones:")
print(ones_arr)

# Creating an array of random numbers
random_arr = np.random.rand(2, 2)
print("Array of random numbers:")
print(random_arr)


Array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array of ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array of random numbers:
[[0.28160119 0.73199411]
 [0.79462541 0.6809455 ]]


Array attributes: shape, size, dtype:

In [3]:
# Shape of an array
print("Shape of the array:", arr.shape)

# Size of an array
print("Size of the array:", arr.size)

# Data type of array elements
print("Data type of the array elements:", arr.dtype)


Shape of the array: (5,)
Size of the array: 5
Data type of the array elements: int64


Reshaping arrays using reshape():

In [4]:
# Reshaping an array
reshaped_arr = arr.reshape(5, 1)
print("Reshaped array:")
print(reshaped_arr)


Reshaped array:
[[1]
 [2]
 [3]
 [4]
 [5]]


Concatenating arrays using concatenate():

In [5]:
# Creating two arrays for concatenation
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# Concatenating arrays along axis 0 (rows)
concatenated_arr = np.concatenate((arr1, arr2), axis=0)
print("Concatenated array along rows:")
print(concatenated_arr)


Concatenated array along rows:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Slicing and indexing arrays:

In [6]:
# Slicing and indexing arrays
print("Sliced array:", arr[2:4])
print("Indexed element:", arr[0])


Sliced array: [3 4]
Indexed element: 1


Element-wise operations: addition, subtraction, multiplication, division

In [7]:
import numpy as np

# Creating two arrays for element-wise operations
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Element-wise addition
addition_result = arr1 + arr2
print("Element-wise addition:")
print(addition_result)

# Element-wise subtraction
subtraction_result = arr1 - arr2
print("Element-wise subtraction:")
print(subtraction_result)

# Element-wise multiplication
multiplication_result = arr1 * arr2
print("Element-wise multiplication:")
print(multiplication_result)

# Element-wise division
division_result = arr1 / arr2
print("Element-wise division:")
print(division_result)


Element-wise addition:
[[ 6  8]
 [10 12]]
Element-wise subtraction:
[[-4 -4]
 [-4 -4]]
Element-wise multiplication:
[[ 5 12]
 [21 32]]
Element-wise division:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


Broadcasting: explaining the concept and its importance

In [8]:
# Broadcasting: performing operations on arrays with different shapes
arr = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 2

# Broadcasting scalar to array
result = arr + scalar
print("Broadcasting:")
print(result)


Broadcasting:
[[3 4 5]
 [6 7 8]]


Vectorized operations for efficiency

In [9]:
# Vectorized operations: applying functions to entire arrays
arr = np.array([[1, 2], [3, 4]])

# Square root of each element
sqrt_result = np.sqrt(arr)
print("Vectorized operation - Square root:")
print(sqrt_result)

# Exponential of each element
exp_result = np.exp(arr)
print("Vectorized operation - Exponential:")
print(exp_result)


Vectorized operation - Square root:
[[1.         1.41421356]
 [1.73205081 2.        ]]
Vectorized operation - Exponential:
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


Creating matrices using arrays.

In [10]:
import numpy as np

# Creating matrices using arrays
matrix_a = np.array([[1, 2, 3], [4, 5, 6]])
matrix_b = np.array([[7, 8, 9], [10, 11, 12]])

print("Matrix A:")
print(matrix_a)
print("Matrix B:")
print(matrix_b)


Matrix A:
[[1 2 3]
 [4 5 6]]
Matrix B:
[[ 7  8  9]
 [10 11 12]]


Matrix multiplication using np.dot():

In [11]:
# Matrix multiplication using np.dot()
matrix_multiplication_result = np.dot(matrix_a, matrix_b.T)  # Transpose of matrix_b for proper multiplication
print("Matrix multiplication result:")
print(matrix_multiplication_result)


Matrix multiplication result:
[[ 50  68]
 [122 167]]


Transpose of a matrix

In [12]:
# Transpose of a matrix
transposed_matrix_a = np.transpose(matrix_a)
print("Transpose of Matrix A:")
print(transposed_matrix_a)


Transpose of Matrix A:
[[1 4]
 [2 5]
 [3 6]]


Computing determinant using np.linalg.det()

In [13]:
import numpy as np

# Define a matrix
matrix = np.array([[1, 2], [3, 4]])

# Computing determinant using np.linalg.det()
determinant = np.linalg.det(matrix)
print("Determinant of the matrix:")
print(determinant)


Determinant of the matrix:
-2.0000000000000004


Solving linear equations using np.linalg.solve()

In [14]:
# Define coefficients and constants matrices
coefficients = np.array([[2, 1], [1, -1]])
constants = np.array([9, 1])

# Solving linear equations using np.linalg.solve()
solution = np.linalg.solve(coefficients, constants)
print("Solution to the system of linear equations:")
print(solution)


Solution to the system of linear equations:
[3.33333333 2.33333333]


Eigenvalues and eigenvectors using np.linalg.eig()

In [15]:
# Define a matrix
matrix = np.array([[1, 2], [2, 1]])

# Compute eigenvalues and eigenvectors using np.linalg.eig()
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)


Eigenvalues:
[ 3. -1.]
Eigenvectors:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


 Solving a system of linear equations

Description: Illustrates how to use NumPy to solve a system of linear equations represented by a coefficient matrix and a constants vector.
Code snippet:

In [16]:
import numpy as np

# Define coefficients and constants matrices
coefficients = np.array([[2, 1], [1, -1]])
constants = np.array([9, 1])

# Solving linear equations using np.linalg.solve()
solution = np.linalg.solve(coefficients, constants)
print("Solution to the system of linear equations:")
print(solution)


Solution to the system of linear equations:
[3.33333333 2.33333333]




 Calculating eigenvalues and eigenvectors

Description: Demonstrates how to compute eigenvalues and eigenvectors of a matrix using NumPy.
Code snippet:

In [17]:
import numpy as np

# Define a matrix
matrix = np.array([[1, 2], [2, 1]])

# Compute eigenvalues and eigenvectors using np.linalg.eig()
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)


Eigenvalues:
[ 3. -1.]
Eigenvectors:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


 Performing principal component analysis (PCA)

Description: Illustrates how to perform principal component analysis (PCA) using NumPy.
Code Example

In [18]:
import numpy as np
from sklearn.decomposition import PCA

# Generate some random data
data = np.random.rand(10, 3)

# Perform PCA
pca = PCA(n_components=2)
principal_components = pca.fit_transform(data)

print("Principal Components:")
print(principal_components)


Principal Components:
[[-0.27541099 -0.04831061]
 [-0.04786002 -0.23945211]
 [ 0.05970382 -0.0841624 ]
 [ 0.09787051 -0.27303136]
 [-0.11078961  0.53082166]
 [-0.17348247 -0.07614221]
 [-0.50225452  0.16444797]
 [-0.34530569 -0.12463641]
 [ 0.62912228  0.21468522]
 [ 0.66840669 -0.06421975]]


E-1: Create a 3x3 identity matrix

In [19]:
import numpy as np

# Creating a 3x3 identity matrix
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:")
print(identity_matrix)


3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


E-2: Compute the dot product of two matrices

In [20]:
import numpy as np

# Define two matrices
matrix_a = np.array([[1, 2, 3], [4, 5, 6]])
matrix_b = np.array([[7, 8], [9, 10], [11, 12]])

# Compute the dot product
dot_product = np.dot(matrix_a, matrix_b)
print("Dot Product of Matrix A and Matrix B:")
print(dot_product)


Dot Product of Matrix A and Matrix B:
[[ 58  64]
 [139 154]]


E-3: Solve a system of linear equations

In [21]:
import numpy as np

# Define the coefficients matrix
coefficients = np.array([[2, 1], [1, -1]])
# Define the constants vector
constants = np.array([9, 1])

# Solve the system of linear equations
solution = np.linalg.solve(coefficients, constants)
print("Solution to the System of Linear Equations:")
print(solution)


Solution to the System of Linear Equations:
[3.33333333 2.33333333]


Solutions for the Exercises...
# Thank You !!